name: direct login

on:
  [push, pull_request, workflow_dispatch]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZ_SP_CREDENTIALS }}
        
        - name: Log in into acr
          run: |
            az acr login --name ${{ secrets.AZ_REGISTRY_NAME }}
            docker pull ${{ secrets.AZ_REGISTRY_LOGIN_SERVER }}/sampleapp